# Generated by Django 6.0.3 on 2026-05-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_add_api_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("pro", "Pro"),
                    ("pro_plus", "Pro+"),
                    ("owner", "Owner"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
