# Generated by Django 6.0.3 on 2026-05-09 22:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pwb", "0003_pwbunit_add_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
