# Generated by Django 6.0.3 on 2026-05-17 08:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwb", "0004_add_certification_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PWBUnitView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source",
                    models.CharField(
                        choices=[("web", "Web"), ("api", "API")], max_length=10
                    ),
                ),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("device_type", models.CharField(blank=True, max_length=10)),
                ("referrer", models.CharField(blank=True, max_length=100)),
                (
                    "pwb_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="pwb.pwbunit",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["pwb_unit", "timestamp"], name="pwb_view_unit_time_idx"
                    ),
                    models.Index(
                        fields=["pwb_unit", "source"], name="pwb_view_unit_src_idx"
                    ),
                ],
            },
        ),
    ]
