# Generated by Django 6.0.3 on 2026-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwb", "0005_pwbunitview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="level",
            field=models.CharField(
                choices=[
                    ("A1 Beginner", "A1 Beginner"),
                    ("A2 Elementary", "A2 Elementary"),
                    ("B1 Intermediate", "B1 Intermediate"),
                    ("B2 Upper-Intermediate", "B2 Upper-Intermediate"),
                    ("C1 Advanced", "C1 Advanced"),
                    ("C2 Advanced Proficiency", "C2 Advanced Proficiency"),
                    ("Native", "Native"),
                    ("Bilingual", "Bilingual"),
                ]
            ),
        ),
    ]
