# Generated by Django 6.0.3 on 2026-05-20 18:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwb", "0007_backfill_language_level_typos"),
    ]

    operations = [
        migrations.CreateModel(
            name="PWBUnitEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("session_id", models.CharField(blank=True, max_length=64)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("device_type", models.CharField(blank=True, max_length=10)),
                ("referrer", models.CharField(blank=True, max_length=200)),
                ("page_url", models.CharField(blank=True, max_length=500)),
                ("time_on_page", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "scroll_depth",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "screen_width",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "screen_height",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "viewport_width",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "viewport_height",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("language", models.CharField(blank=True, max_length=20)),
                ("timezone", models.CharField(blank=True, max_length=60)),
                (
                    "color_scheme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dark", "Dark"),
                            ("light", "Light"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4g", "4G"),
                            ("3g", "3G"),
                            ("2g", "2G"),
                            ("slow-2g", "Slow 2G"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                ("pdf_downloaded", models.BooleanField(default=False)),
                ("email_clicked", models.BooleanField(default=False)),
                ("phone_clicked", models.BooleanField(default=False)),
                ("links_clicked", models.JSONField(blank=True, default=list)),
                ("sections_viewed", models.JSONField(blank=True, default=list)),
                (
                    "pwb_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="pwb.pwbunit",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["pwb_unit", "timestamp"], name="pwb_eng_unit_time_idx"
                    )
                ],
            },
        ),
    ]
